### PR TITLE
Fix overrides array in DoctrineORMMapper

### PR DESCRIPTION
**Pull request by archer-developer**
Fix last array argument in DoctrineORMMapper.php in consructor.

### CODE REVIEW

**Comment by core23** [comment]
Good catch!

Refs https://github.com/sonata-project/SonataEasyExtendsBundle/pull/97

**Comment by greg0ire** [comment]
Can you associate your email address with your GH account? Also, a unit test would be great.

**Comment by core23** [comment]
We don't need a test for this, because this line was just missing in my PR.

**Comment by archer-developer** [comment]
> Can you associate your email address with your GH account?
Yes, I did it right now

**Comment by greg0ire** [comment]
I asked for a test because IMO this should have been caught. Totally optional though since it isn't @archer-developer's mistake.

**Comment by greg0ire** [comment]
> Yes, I did it right now 

Didn't work. I'm talking about your itmhouse.com email address.

**Pull request merged**
